package org.audiolord.model;

import net.sf.persist.annotations.Column;

/**
 * Represents a music library
 * @author Jacek Furmankiewicz
 */
public class Library {

	private int libraryId;
	private String path;
	/**
	 * @return the id
	 */
	@Column(autoGenerated=true)
	public int getLibraryId() {
		return libraryId;
	}
	/**
	 * @param id the id to set
	 */
	public void setLibraryId(int id) {
		this.libraryId = id;
	}
	/**
	 * @return the path
	 */
	public String getPath() {
		return path;
	}
	/**
	 * @param path the path to set
	 */
	public void setPath(String path) {
		this.path = path;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return path.hashCode();
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		return getPath().equals(obj);
	}
	
	
}
